// src/app/components/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { User } from '../../models/user.model';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  signupForm!: FormGroup;
  // Options for gender and interests
  genders = ['Male', 'Female', 'Other'];
  interests = ['Sports', 'Reading', 'Gaming', 'Music', 'Movies'];

  isModalOpen: boolean = false; // Controls signup validation error modal visibility
  modalMessages: string[] = []; // Messages to display in the modal
  showPassword: boolean = false;
  showConfirmPassword: boolean = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
    // Initialize the signup form with form controls and validators
    this.signupForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^\d{10}$/)]], // 10 digit phone number
      gender: ['', Validators.required],
      interests: this.fb.array([], Validators.required), // Array of checkboxes
      password: ['', [
        Validators.required,
        Validators.minLength(6),
        Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}$/)
      ]]
    });
  }

  /**
   * Getter for easy access to form fields in the template.
   */
  get f() { return this.signupForm.controls; }

  /**
   * Handles changes to interest checkboxes.
   * @param event The change event.
   */
  onInterestChange(event: any): void {
    const interestsArray = this.signupForm.controls['interests'] as FormArray;
    if (event.target.checked) {
      interestsArray.push(this.fb.control(event.target.value));
    } else {
      const index = interestsArray.controls.findIndex(x => x.value === event.target.value);
      interestsArray.removeAt(index);
    }
  }

  /**
   * Handles form submission for user signup.
   */
  onSubmit(): void {
    this.modalMessages = []; // Clear previous messages

    // If form is invalid, collect error messages and display in modal
    if (this.signupForm.invalid) {
      this.collectFormErrors(this.signupForm);
      this.isModalOpen = true;
      return;
    }

    const { name, email, phoneNumber, gender, interests, password } = this.signupForm.value;

    const newUser: User = {
      id: '', // Will be generated by AuthService
      name,
      email,
      phoneNumber,
      gender,
      interests,
      password // Temporarily send password for mock signup, real apps would hash
    };

    this.authService.signup(newUser).subscribe(
      success => {
        if (success) {
          alert('Signup successful! You are now logged in.');
          this.router.navigate(['/products']); // Redirect to products page on successful signup
        } else {
          this.modalMessages.push('Signup failed: Email already registered.');
          this.isModalOpen = true;
        }
      },
      error => {
        this.modalMessages.push('An error occurred during signup. Please try again.');
        this.isModalOpen = true;
        console.error('Signup error:', error);
      }
    );
  }

  /**
   * Collects all validation error messages from the form and its controls.
   * @param formGroup The form group to inspect for errors.
   */
  private collectFormErrors(formGroup: FormGroup | FormArray): void {
    Object.keys(formGroup.controls).forEach(key => {
      const control = formGroup.get(key);
      if (control instanceof FormGroup || control instanceof FormArray) {
        this.collectFormErrors(control); // Recursively check nested form groups/arrays
      } else if (control && control.invalid && control.errors) {
        for (const errorKey in control.errors) {
          if (control.errors.hasOwnProperty(errorKey)) {
            let message = '';
            switch (errorKey) {
              case 'required':
                message = `${this.capitalizeFirstLetter(key)} is required.`;
                break;
              case 'email':
                message = `Invalid email format.`;
                break;
              case 'minlength':
                message = `${this.capitalizeFirstLetter(key)} must be at least ${control.errors['minlength'].requiredLength} characters.`;
                break;
              case 'pattern':
                if (key === 'password') {
                  message = 'Password must contain at least one uppercase, one lowercase, one number, and one special character.';
                } else if (key === 'phoneNumber') {
                  message = 'Phone number must be 10 digits.';
                }
                break;
              default:
                message = `${this.capitalizeFirstLetter(key)} has an error.`;
                break;
            }
            this.modalMessages.push(message);
          }
        }
      }
    });
  }

  /**
   * Helper function to capitalize the first letter of a string.
   * @param str The string to capitalize.
   * @returns The capitalized string.
   */
  private capitalizeFirstLetter(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Closes the signup validation error modal.
   */
  closeModal(): void {
    this.isModalOpen = false;
    this.modalMessages = [];
  }

  /**
   * Toggles password visibility
   */
  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  /**
   * Toggles confirm password visibility
   */
  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }
}

import { FormArray } from '@angular/forms'; // Moved import to bottom to satisfy linter, will move to top on next replace
